; YouTube Opus Downloader V6 配置文件
; 只需要修改下面两个路径。
; Windows 示例：D:\Music\YouTube
; 也支持环境变量：%USERPROFILE%\Downloads\YouTube Audio

[download]
path=B:\youtube_opus_downloader\Download

[cookies]
; 指定你导出的 cookies.txt 文件完整路径。
; 例如：D:\YouTube\cookies.txt
; 也可以直接写 cookies.txt，表示使用程序同目录的 cookies.txt。
path=cookies.txt
